#!/usr/bin/env bash
set -e
echo "ALL IN!"
# Main tune clusters
# and fvs (outside)
lans=() # Include any language you want from {ch jp he ar}
anns=(-+ +- ++ bs) #Baseline no need as already created

for l in "$@" 
do 
    lans+=("$l") 
done 
echo "Languages are: ${lans[*]}"

for lan in ${lans[*]}
do
    for ann in ${anns[*]}
    do  
        t_steps=15000
        if [ $lan = 'he' ]
        then
            t_steps=5000
        fi
        bash ez_training_script $lan $ann $t_steps 0.8 brnn 2 4 5 7 9 10 12 15
    done
done
