#!/usr/bin/env bash
set -e
echo "ALL IN!"
# Main tune clusters
# and fvs (outside)
anns=(bs -+ +- ++) #Baseline no need as already created

lan=$1
shift
src=$1
shift
tgt=$1
shift

for ann in ${anns[*]}
do  
    t_steps=40000
    bash ez_training_script $lan $ann $t_steps 0.6 brnn $src $tgt 2 5 7 10 12 15
done

