#!/usr/bin/env bash
set -e
# A script for running the translation commands for the best checkpoint of each model
# Arguments: lan, sequence of clusters

main_dir=/disk/ocean/lhe/transliteration/nmt-py
# strings for necessary file names 
src="en" 
_tst="_tst" 
_tst_="_tst_"
step="_step_"

lan=$1
echo "Language: $lan"
shift

if [ $lan = "ar" ]
then
   src="ar"
fi

clusters=()
for c in "$@"
do
    clusters+=($c)
done
echo "Clusters are: ${clusters[*]}"
echo "Number of clusters: ${#clusters[*]}"


# Get the best checkpoint for baseline
echo "Best checkpoint_step for bs:"
read bst

anns=(m-+ m+- m++)
# Read best checkpoints for annotated models
for ann in ${anns[*]}
do
    echo "$ann FEED BEST CHECKPOINTS"
    declare -A model
    echo "Best checkpoint_setps in $ann are:"
    for c in ${clusters[*]}
    do
        echo "For cluster $c"
        read ckp
        model[$c]="$ckp"
    done

    echo "Repeat: Best checkpoint_setps in $ann are:"
    for c in ${clusters[*]} 
    do     
        echo "$c : ${model[$c]}"
    done
    echo "$ann DONE FEED"

    mkdir $main_dir/best_results/$lan/$ann
    # Go to the working directory
    cd $main_dir/models/$lan/$ann
    for i in ${clusters[*]}
    do
        cd $main_dir/models/$lan/$ann/$i
        best=${model[$i]} # extract the best checkpoint for cluster i
        # model: $i$step$best.pt e.g. 2_step_15000.pt
        python $main_dir/OpenNMT-py/translate.py \
        -model $i$step$best.pt \
        -src data/*$src$_tst* \
        -output infer/$i$_tst_$best.txt \
        -replace_unk \
        -verbose \
        -gpu 1;
        
        # copy the best results to the best_results
        cd infer
        cp -r *$best* $main_dir/best_results/$lan/$ann
    done
    echo "$i FINISH!"
done

# Translate test file with the best ckp
# For baseline
cd $main_dir/models/$lan/bs
python $main_dir/OpenNMT-py/translate.py \
-model bs_step_$bst.pt \
-src data/*$src$_tst* \
-output infer/bs$_tst_$bst.txt \
-replace_unk \
-verbose \
-gpu 1;

cd infer
mkdir $main_dir/best_results/$lan/bs
cp -r *$bst* $main_dir/best_results/$lan/bs

echo "ALL FINISH!"
