data:
  train_features_file: /disk/ocean/lhe/en2chi/Data/15cls/en2chi_tra_eng_15cls.txt
  train_labels_file: /disk/ocean/lhe/en2chi/Data/15cls/en2chi_tra_chi_15cls.txt
  eval_features_file: /disk/ocean/lhe/en2chi/Data/15cls/en2chi_dev_eng_15cls.txt
  eval_labels_file: /disk/ocean/lhe/en2chi/Data/15cls/en2chi_dev_chi_15cls.txt
  source_words_vocabulary: /disk/ocean/lhe/en2chi/Vocab/15cls/eng.txt
  target_words_vocabulary: /disk/ocean/lhe/en2chi/Vocab/15cls/chi.txt

model_dir: /disk/ocean/lhe/en2chi/NMT_large/15cls
