data:
  train_features_file: /disk/ocean/lhe/en2chi/Data/baseline/en2chi_tra_eng.txt
  train_labels_file: /disk/ocean/lhe/en2chi/Data/baseline/en2chi_tra_chi.txt
  eval_features_file: /disk/ocean/lhe/en2chi/Data/baseline/en2chi_dev_eng.txt
  eval_labels_file: /disk/ocean/lhe/en2chi/Data/baseline/en2chi_dev_chi.txt
  source_words_vocabulary: /disk/ocean/lhe/en2chi/Vocab/baseline/en2chi_tra_eng_vocab.txt
  target_words_vocabulary: /disk/ocean/lhe/en2chi/Vocab/baseline/en2chi_tra_chi_vocab.txt

model_dir: /disk/ocean/lhe/en2chi/NMT_large/baseline
