# Default OpenNMT parameters from the Lua version.

params:
  optimizer: AdagradOptimizer
  learning_rate: 0.2
  param_init: 0.1
  clip_gradients: 5.0
  decay_type: exponential_decay
  decay_rate: 0.7
  decay_steps: 250
  start_decay_steps: 9000
  beam_width: 5
  maximum_iterations: 250

train:
  batch_size: 50
  bucket_width: 1
  save_checkpoints_steps: 50
  keep_checkpoint_max: 20
  save_summary_steps: 50
  train_steps: 18000
  maximum_features_length: 50
  maximum_labels_length: 50

  # Consider setting this to -1 to match the number of training examples.
  sample_buffer_size: -1

eval:
  eval_delay: 10800  # Every 3 hrs.

infer:
  batch_size: 30
