#!/usr/bin/env bash
# Must be used in the infer directory

echo "Language:"
read lan 
echo "Training steps:"
read t_steps
let i=t_steps-900
echo "Clusters: {bs 2 5 10 15}"
read cls
_dev_="_dev_"
_dev="_dev"

# copy the target dev/tst files to the infer directory
_dev="_dev"
_tst="_tst"
if [ $lan != "ar" ]
then
   cp /disk/ocean/lhe/transliteration/nmt-py/data/$lan/bs/$lan$_dev.txt .
   cp /disk/ocean/lhe/transliteration/nmt-py/data/$lan/bs/$lan$_tst.txt .
fi

if [ $lan = "ar" ]
then
   /disk/ocean/lhe/transliteration/nmt-py/data/$lan/bs/en_dev.txt .
   /disk/ocean/lhe/transliteration/nmt-py/data/$lan/bs/en_tst.txt .
fi

# -----WER-------  
# (In python3 venv)

while [ $i -le $t_steps ]
do 
  python wer.py $cls$_dev_$i.txt $lan$_dev.txt >> wer.txt 
  echo $i >> wer.txt
  let i+=100
done  
# -----CER-------
let i=t_steps-900  
while [ $i -le $t_steps ]
do
   wer $lan$_dev.txt original_$cls$_dev_$i.txt >> cer.txt
   echo $i >> cer.txt
   let i+=100
done

python cer.py $t_steps

