#!/usr/bin/env bash
set -e
# Must be used in the infer directory

src=$1
shift 
tgt=$1
shift
echo "Direction $src -> $tgt"

t_steps=$1
shift
echo "Training steps: $t_steps"

let i=t_steps-900
cls=$1
shift
echo "Clusters: $cls"

main_dir=/disk/ocean/lhe/transliteration/nmt-py #The same main dir as in the ez-training script

_dev_="_dev_"
_dev="_dev"
_dev="_dev"
_tst="_tst"

# copy the target dev/tst files to the infer directory
cp $main_dir/data/$lan/bs/$tgt$_dev.txt .
cp $main_dir/data/$lan/bs/$tgt$_tst.txt .
   

# -----WER-------  
# (In python3 venv)

while [ $i -le $t_steps ]
do 
  python wer.py $cls$_dev_$i.txt $tgt$_dev.txt >> wer.txt 
  echo $i >> wer.txt
  let i+=100
done  
# -----CER-------
let i=t_steps-900  
while [ $i -le $t_steps ]
do
   wer $tgt$_dev.txt original_$cls$_dev_$i.txt >> cer.txt
   echo $i >> cer.txt
   let i+=100
done

python cer.py $t_steps

python bst_ckp.py wer.txt cer-clean.txt
